In [19]:
import pandas as pd
import numpy as np
import string

In [23]:
wordle_words = pd.read_csv('Word Data/wordle_words.csv')
wordle_words

        word       count
0      about  1226734006
1      other   978481319
2      which   810514085
3      their   782849411
4      there   701170205
...      ...         ...
39928  goovo       12711
39929  goova       12711
39930  goolh       12711
39931  gooek       12711
39932  golgw       12711

[39933 rows x 2 columns]

In [24]:
wordle_words['first'] = wordle_words['word'].str[0]
wordle_words['second'] = wordle_words['word'].str[1]
wordle_words['third'] = wordle_words['word'].str[2]
wordle_words['fourth'] = wordle_words['word'].str[3]
wordle_words['fifth'] = wordle_words['word'].str[4]
wordle_words

        word       count first second third fourth fifth
0      about  1226734006     a      b     o      u     t
1      other   978481319     o      t     h      e     r
2      which   810514085     w      h     i      c     h
3      their   782849411     t      h     e      i     r
4      there   701170205     t      h     e      r     e
...      ...         ...   ...    ...   ...    ...   ...
39928  goovo       12711     g      o     o      v     o
39929  goova       12711     g      o     o      v     a
39930  goolh       12711     g      o     o      l     h
39931  gooek       12711     g      o     o      e     k
39932  golgw       12711     g      o     l      g     w

[39933 rows x 7 columns]

In [25]:
wordle_words.to_csv('Word Data/wordle_words.csv')