In [1]:
import pandas as pd
import numpy as np
import string
import itertools
import time

In [3]:
raw_wordle_words = pd.read_csv('Word Data/wordle_words.csv')
wordle_words_counted = pd.read_csv('Word Data/counted_wordle_words.csv')
wordle_words_counted = wordle_words_counted.drop(columns=['Unnamed: 0','count'])
wordle_words_counted

['GGGGG',
 'GGGGY',
 'GGGGN',
 'GGGYG',
 'GGGYY',
 'GGGYN',
 'GGGNG',
 'GGGNY',
 'GGGNN',
 'GGYGG',
 'GGYGY',
 'GGYGN',
 'GGYYG',
 'GGYYY',
 'GGYYN',
 'GGYNG',
 'GGYNY',
 'GGYNN',
 'GGNGG',
 'GGNGY',
 'GGNGN',
 'GGNYG',
 'GGNYY',
 'GGNYN',
 'GGNNG',
 'GGNNY',
 'GGNNN',
 'GYGGG',
 'GYGGY',
 'GYGGN',
 'GYGYG',
 'GYGYY',
 'GYGYN',
 'GYGNG',
 'GYGNY',
 'GYGNN',
 'GYYGG',
 'GYYGY',
 'GYYGN',
 'GYYYG',
 'GYYYY',
 'GYYYN',
 'GYYNG',
 'GYYNY',
 'GYYNN',
 'GYNGG',
 'GYNGY',
 'GYNGN',
 'GYNYG',
 'GYNYY',
 'GYNYN',
 'GYNNG',
 'GYNNY',
 'GYNNN',
 'GNGGG',
 'GNGGY',
 'GNGGN',
 'GNGYG',
 'GNGYY',
 'GNGYN',
 'GNGNG',
 'GNGNY',
 'GNGNN',
 'GNYGG',
 'GNYGY',
 'GNYGN',
 'GNYYG',
 'GNYYY',
 'GNYYN',
 'GNYNG',
 'GNYNY',
 'GNYNN',
 'GNNGG',
 'GNNGY',
 'GNNGN',
 'GNNYG',
 'GNNYY',
 'GNNYN',
 'GNNNG',
 'GNNNY',
 'GNNNN',
 'YGGGG',
 'YGGGY',
 'YGGGN',
 'YGGYG',
 'YGGYY',
 'YGGYN',
 'YGGNG',
 'YGGNY',
 'YGGNN',
 'YGYGG',
 'YGYGY',
 'YGYGN',
 'YGYYG',
 'YGYYY',
 'YGYYN',
 'YGYNG',
 'YGYNY',
 'YGYNN',
 'YGNGG',
 'YGNGY',
 'YGNGN',
 'YGNYG',
 'YGNYY',
 'YGNYN',
 'YGNNG',
 'YGNNY',
 'YGNNN',
 'YYGGG',
 'YYGGY',
 'YYGGN',
 'YYGYG',
 'YYGYY',
 'YYGYN',
 'YYGNG',
 'YYGNY',
 'YYGNN',
 'YYYGG',
 'YYYGY',
 'YYYGN',
 'YYYYG',
 'YYYYY',
 'YYYYN',
 'YYYNG',
 'YYYNY',
 'YYYNN',
 'YYNGG',
 'YYNGY',
 'YYNGN',
 'YYNYG',
 'YYNYY',
 'YYNYN',
 'YYNNG',
 'YYNNY',
 'YYNNN',
 'YNGGG',
 'YNGGY',
 'YNGGN',
 'YNGYG',
 'YNGYY',
 'YNGYN',
 'YNGNG',
 'YNGNY',
 'YNGNN',
 'YNYGG',
 'YNYGY',
 'YNYGN',
 'YNYYG',
 'YNYYY',
 'YNYYN',
 'YNYNG',
 'YNYNY',
 'YNYNN',
 'YNNGG',
 'YNNGY',
 'YNNGN',
 'YNNYG',
 'YNNYY',
 'YNNYN',
 'YNNNG',
 'YNNNY',
 'YNNNN',
 'NGGGG',
 'NGGGY',
 'NGGGN',
 'NGGYG',
 'NGGYY',
 'NGGYN',
 'NGGNG',
 'NGGNY',
 'NGGNN',
 'NGYGG',
 'NGYGY',
 'NGYGN',
 'NGYYG',
 'NGYYY',
 'NGYYN',
 'NGYNG',
 'NGYNY',
 'NGYNN',
 'NGNGG',
 'NGNGY',
 'NGNGN',
 'NGNYG',
 'NGNYY',
 'NGNYN',
 'NGNNG',
 'NGNNY',
 'NGNNN',
 'NYGGG',
 'NYGGY',
 'NYGGN',
 'NYGYG',
 'NYGYY',
 'NYGYN',
 'NYGNG',
 'NYGNY',
 'NYGNN',
 'NYYGG',
 'NYYGY',
 'NYYGN',
 'NYYYG',
 'NYYYY',
 'NYYYN',
 'NYYNG',
 'NYYNY',
 'NYYNN',
 'NYNGG',
 'NYNGY',
 'NYNGN',
 'NYNYG',
 'NYNYY',
 'NYNYN',
 'NYNNG',
 'NYNNY',
 'NYNNN',
 'NNGGG',
 'NNGGY',
 'NNGGN',
 'NNGYG',
 'NNGYY',
 'NNGYN',
 'NNGNG',
 'NNGNY',
 'NNGNN',
 'NNYGG',
 'NNYGY',
 'NNYGN',
 'NNYYG',
 'NNYYY',
 'NNYYN',
 'NNYNG',
 'NNYNY',
 'NNYNN',
 'NNNGG',
 'NNNGY',
 'NNNGN',
 'NNNYG',
 'NNNYY',
 'NNNYN',
 'NNNNG',
 'NNNNY',
 'NNNNN']

In [ ]:
# Probability of result = number of count/total words
# Information of result = -log(number of count/total words)
# Entropy of word = -sum(prob * information)

In [7]:
total_count = wordle_words_counted.drop(columns=['word']).sum(axis=1)
total_count = total_count[0]
total_count

,word,GGGGG Count,GGGGY Count,GGGGN Count,GGGYG Count,GGGYY Count,GGGYN Count,GGGNG Count,GGGNY Count,GGGNN Count,...,NNNGG Count,NNNGY Count,NNNGN Count,NNNYG Count,NNNYY Count,NNNYN Count,NNNNG Count,NNNNY Count,NNNNN Count,Total Count
0,about,1,0,0,0,0,0,1,0,4,...,4,11,86,34,140,452,139,431,1347,8754
1,other,1,0,0,0,0,0,0,0,0,...,213,166,511,25,422,714,46,534,1292,8754
2,which,1,0,0,0,0,0,1,14,0,...,0,0,128,0,0,656,0,0,4259,8754
3,their,1,0,1,0,0,0,1,2,9,...,9,82,203,17,166,535,69,619,1355,8754
4,there,1,1,0,0,2,0,3,7,0,...,0,0,180,0,0,782,0,0,2093,8754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8749,sevak,1,0,0,0,0,0,0,0,2,...,12,23,271,38,96,962,55,85,1034,8754
8750,maist,1,0,0,0,0,5,0,0,5,...,28,12,110,40,286,883,88,278,1093,8754
8751,hully,1,0,2,0,0,1,0,0,0,...,0,0,0,0,0,0,501,172,3943,8754
8752,intil,1,0,0,1,0,3,0,0,0,...,0,0,0,0,0,0,175,968,2517,8754
8753,toits,1,0,1,1,0,1,0,0,0,...,0,0,0,0,0,0,872,500,1634,8754

In [24]:
def calculate_entropy(word):
    counts = wordle_words_counted[wordle_words_counted["word"]==word].drop(columns=["word"])
    entropy = counts.apply(lambda x: x/total_count * -np.log2(x/total_count), axis=1).sum(axis=1)
    return entropy

calculate_entropy("about")

C:\Users\davey\Documents\Code\Personal\Wordle Bot\.venv\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

0    4.520243
dtype: float64

In [27]:
wordle_words_counted["entropy"] = wordle_words_counted.drop(columns=["word"]).apply(lambda x: x/total_count * -np.log2(x/total_count), axis=1).sum(axis=1)
wordle_words_counted

C:\Users\davey\Documents\Code\Personal\Wordle Bot\.venv\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)

,word,GGGGG Count,GGGGY Count,GGGGN Count,GGGYG Count,GGGYY Count,GGGYN Count,GGGNG Count,GGGNY Count,GGGNN Count,...,NNNGG Count,NNNGY Count,NNNGN Count,NNNYG Count,NNNYY Count,NNNYN Count,NNNNG Count,NNNNY Count,NNNNN Count,entropy
0,about,1,0,0,0,0,0,1,0,4,...,4,11,86,34,140,452,139,431,1347,4.520243
1,other,1,0,0,0,0,0,0,0,0,...,213,166,511,25,422,714,46,534,1292,4.912933
2,which,1,0,0,0,0,0,1,14,0,...,0,0,128,0,0,656,0,0,4259,2.980960
3,their,1,0,1,0,0,0,1,2,9,...,9,82,203,17,166,535,69,619,1355,5.053575
4,there,1,1,0,0,2,0,3,7,0,...,0,0,180,0,0,782,0,0,2093,4.365915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8749,sevak,1,0,0,0,0,0,0,0,2,...,12,23,271,38,96,962,55,85,1034,4.801934
8750,maist,1,0,0,0,0,5,0,0,5,...,28,12,110,40,286,883,88,278,1093,5.338422
8751,hully,1,0,2,0,0,1,0,0,0,...,0,0,0,0,0,0,501,172,3943,3.392963
8752,intil,1,0,0,1,0,3,0,0,0,...,0,0,0,0,0,0,175,968,2517,3.929866
8753,toits,1,0,1,1,0,1,0,0,0,...,0,0,0,0,0,0,872,500,1634,4.797506

In [28]:
wordle_words_counted.to_csv('Word Data/wordle_words_entropy.csv')